version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo-breezy
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: breezy_auth

  auth-service:
    build:
      context: ./backend/auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy_auth
      - AUTH_TOKEN=supersecretkey
      - EMAIL_USER=ton.email@gmail.com
      - EMAIL_PASS=ton_mot_de_passe_ou_app_password
      - NODE_ENV=development
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - auth-service

volumes:
  mongo_data: