import "./globals.css";
import { Archivo } from "next/font/google";
import Navbar from "../components/Navbar";
import FooterSwitch from "../components/FooterSwitcher/FooterSwitcher";

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body >
        <Navbar />
        {children}
        <FooterSwitch />
      </body>
    </html>
  );
}